### ISSUE TITLE
Building master/head fails

### ISSUE THREAD

**Issue by nandub** [stevedekorte/io#198]
I'm using Io formula from homebrew to build head

I'm getting this error

```
/tmp/homebrew-io-HEAD-pyoB/addons/SQLite3/source/IoSQLite3.c:213:2: error: void function 'IoSQLite3_justOpen' should not return a value [-Wreturn-type]
        return self;
        ^      ~~~~
```
See https://github.com/mxcl/homebrew/issues/11276 for more info.  This pull request removes the libsgml dependency.  It compiles fine with latest 2011.09.12 tarball.
